version: "3"
services: 
  app:
    build: .
    container_name: api
    ports:
      - "9000:9000"
    volumes:
      - .:/go/src/
  # db:
    # image: mongo:4.2
    # container_name: db
    # restart: always
    # ports:
    #   - ${DATABASE_PORT}:27017
    # environment:
    #   MONGO_INITDB_DATABASE: ${DATABASE_HOST}
    #   MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
    #   MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}